---
title: "frist chapter - Horizontal distribution"
author: "Ricardo Silva"
date: "26/11/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup}
knitr::opts_chunk$set(
	fig.height = 5,
	fig.width = 8,
	dpi = 180,
	message = FALSE,
	warning = FALSE,
	cache = TRUE,
	echo = TRUE
)
```

```{r CLEAR EVERYTHING, eval=FALSE, include=FALSE}
# unload all non-base packages
lapply(names(sessionInfo()$otherPkgs), function(pkgs)
  detach(
    paste0('package:', pkgs),
    character.only = T,
    unload = T,
    force = T
))

rm(list=ls())
```

```{r packages}
# set the working directory
folder_path <- getwd()
setwd(paste0(folder_path,"/data"))

pcks <- c("tidyverse", "phyloseq", 'vegan', "geosphere","skimr", 'tidymodels', 'tidytext', "egg")

if(sum(as.numeric(!pcks %in% installed.packages())) != 0){
  installation <- pcks[!pcks %in% installed.packages()]
  for(i in 1:length(installation)) {
    install.packages(installation, dependencies = T)
    break()}
  sapply(pcks, require, character = T) 
} else {
  sapply(pcks, require, character = T) 
}

# main packs to start with
# BiocManager::install("ade4") # -> to get packages from bioconductor website
#require(ALDEx2) # used for per OTU comparisons
#library(CoDaSeq)
#library(propr) # used for correlation calculation
#library(QsRutils)
#library(zCompositions)
#library(ggpubr)
# load my functions

source('script/my_functions.R')
source('script/theme_publication.R')

```

# Horizontal distribution

# Bacterial Community

## Data preparation and preprocessing

```{r data}
# Data preparation 
# abundance table 
abund.df <- read.csv("SPE_bac_MH16.csv",  row.names = 1, head = TRUE)

# taxonomy table
TAXdf <- read.csv("tax_bac_2016.csv", row.names = 1, head = TRUE)
TAXdf <- TAXdf 
str(TAXdf)
sum(is.na(TAXdf))
apply(TAXdf, 2, function(x) any(is.na(x)))
bac.seqs <- TAXdf %>% rownames_to_column("otu") %>% select(otu, seq)
TAXdf <- TAXdf  %>% 
  rownames_to_column('id') %>%
  mutate(across(everything(), ~replace_na(.x, "unknown"))) %>% 
  filter(Phylum != 'unknown') %>%
  mutate(across(where(is.character), as.factor)) %>%
  select(-seq) %>%
  column_to_rownames('id')

# make sure that the same OTUs are the same in both datasets
abund.df <- base::subset(abund.df, row.names(abund.df) %in% row.names(TAXdf))

## meta data
MH_env <- read.csv("MH16_env.csv", row.names = 1)
# str(MH_env)
MH_env$Depth <- as.factor(MH_env$Depth) # Depth as factor = treatment
```

```{r data prep}
abund.df.surf <- abund.df %>% dplyr::select(ends_with("3"))
out.mh.column <- c("ocean_3", "KR_3", "GR_3")
abund.surf <- abund.df %>% select(ends_with("3")) %>% 
  select(-all_of(out.mh.column))
TAX.surf <- base::subset(TAXdf, row.names(TAXdf) %in% row.names(abund.surf))
MH_env.surf <-  MH_env %>% rownames_to_column(var = "sample") %>%
  filter(Depth == 3) %>% filter(!sample_id %in% out.mh.column) %>%
  mutate(across(where(is.character), as.factor)) 
#  mutate_if(is.character,as.factor) %>%
str(MH_env.surf)  

pseq.surf <- phyloseq(otu_table(as.matrix(as.data.frame(abund.surf)), taxa_are_rows = TRUE),
                      tax_table(as.matrix(TAX.surf)),sample_data(MH_env.surf))
# Filter out any OTUs that are non bacterial
pseq.surf <- pseq.surf %>%
  subset_taxa(
    Kingdom == "Bacteria" &
      Family  != "mitochondria" &
      Class   != "Chloroplast"
  )
abund.surf <- data.frame(otu_table(pseq.surf))

```

## Environmental Parameters and Diversity indices

Summary table

```{r}
# skimr package 
summary_df <- MH_env %>% 
  filter(Depth == 3) %>%
  #group_by(region) %>%
  select (Temperature:Carbon,AOB_copies, AOA_copies, nosZ_copies, Chao1,Shannon) %>%
  skimr::skim()

summary_df %>% 
  select(skim_variable, numeric.mean:numeric.p0, numeric.p100) %>%
  rename(variable = skim_variable) %>%
  rename_with(., ~str_replace(.,'numeric.','')) %>%
  rename(min = p0) %>%
  rename(max = p100)

```

```{r env and alpha div, eval=FALSE, include=FALSE}
# Plotting
env.surf.anova1 <- plot_anova_env(pseq.surf, grouping_column = "region", pValueCutoff = 0.001, 
               select.variables = c("DO","Salinity","Temperature", "Nitrogen", "Carbon", "TSSmean"))
env.surf.anova1 +  theme_Publication() + 
  labs(title="Environmental Parameters - 3 meters Depth") + theme(legend.position = "none") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + xlab("Region")

env.surf.anova2 <- plot_anova_env(pseq.surf, grouping_column = "region", pValueCutoff = 0.01, 
                                  select.variables = c("AOB_copies","AOA_copies","nosZ_copies" , "Chao1", "Shannon"))

env.surf.anova2 +  theme_Publication() + 
  labs(title="Nitrogen-related genes\nDiversity Indices - 3 meters Depth") + theme(legend.position = "none") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+xlab("Region")

# if it's not working use the code below (probably there is no significance) -> use print.lines = FALSE
env.surf.anova.arc <- plot_anova_env(pseq.surf, grouping_column = "region", pValueCutoff = 0.001,
                                     select.variables = c("AOB_copies","AOA_copies","nosZ_copies" , "Chao1", "Shannon"), print.lines = FALSE)

# statistical summary (tables)
combDF.surf <- MH_env.surf %>% drop_na() %>%
  dplyr::select("region", "DO","Salinity","Temperature", "Carbon", "Nitrogen", "CN", "TSSmean", "AOB_copies", "AOA_copies", "nosZ_copies", "Chao1","Shannon")
#combDF.surf[, 9:11] <- log(combDF.surf[, 9:11],2) # log transformation of AOA, AOB and nosZ
data_long <- combDF.surf %>% gather(key="env_par", value="value", -region)
# sorting x-axis for plot
data_long$region <- factor(data_long$region, levels=c("north", "central", "south"))
data_long$env_par <- factor(data_long$env_par, levels=c("DO","Salinity","Temperature", "Carbon", "Nitrogen", "CN", "TSSmean", "AOB_copies", "AOA_copies", "nosZ_copies", "Chao1","Shannon"))

p.meta.region.surf <- data_long %>% 
  ggplot(aes(x=region, y=value)) +
  geom_boxplot(aes(color = region), outlier.color = NA) +
 # scale_x_discrete(limits = rev(levels(data_long$region)))+
  geom_jitter(aes(color = region), alpha=0.6) +
 # scale_color_manual(values = cols_region) +
  facet_wrap(~ env_par, scales = "free") +
  labs(y = "") +
  theme(legend.position = "none") 

p.meta.region.surf + scale_colour_Publication() + theme_Publication() + 
  labs(title="Environmental Parameters - 3 meters Depth")+theme(legend.position = "none")
  
# STATS  
# making summary tables (ANOVA and Tukey)
stats.sum.surf <- data_long %>% 
  nest(data = c(region, value)) %>% 
  mutate(model = map(data, ~anova(lm(value ~ region, .))), 
         tidy = map(model, broom::tidy)) %>% 
  select(env_par, tidy) %>% 
  unnest(tidy)
write.csv(stats.sum.surf, "output/anova_env_summary_surf.csv")

stats.sum.surf.Tukey <- data_long %>% 
  nest(data = c(region, value)) %>% 
  mutate(model = map(data, ~TukeyHSD(aov(lm(value ~ region, .)))), 
         tidy = map(model, broom::tidy)) %>% 
  select(env_par, tidy) %>% 
  unnest(tidy)
write.csv(stats.sum.surf.Tukey, "output/anova_env_summary_surf_tukey.csv")
```

## Beta diversity

```{r data prep}
# filtering data and clr-transformation
min.prop=0.001 # minimum proportion in any sample (default)
min.occurrence=0.001 # minimum occurrence across all samples (sparsity filter)
# only surface and without outliers
d.filt0.mh.surf <- CoDaSeq::codaSeq.filter(abund.surf, min.prop=0, min.occurrence=0, samples.by.row=FALSE)
d.filt.mh.surf <- CoDaSeq::codaSeq.filter(d.filt0.mh.surf, min.prop=min.prop, max.prop=1, min.occurrence=min.occurrence, samples.by.row=FALSE)
d.zero.hand.mh.surf <- t(zCompositions::cmultRepl(t(d.filt.mh.surf), label =0, method="CZM")) # filtered
d.clr.abund.filt.mh.surf <- CoDaSeq::codaSeq.clr(d.zero.hand.mh.surf, samples.by.row = FALSE)
TAX.filt.mh.surf <- base::subset(TAXdf, row.names(TAXdf) %in% row.names(d.filt.mh.surf))
```

```{r stats and plotting}
# statistical testing
# performing PerMANOVA to test the hypothesis that bacterial communities within each group
# are more similar to each other than those under other groups. 
# perform PerMANOVA using Euclidean distances (for RDA)
perm.surf <- vegan::adonis2(dist(t(d.clr.abund.filt.mh.surf), method='euclidean') ~ region, 
                       data=MH_env.surf, permutations = 9999) # 3m depth without outliers
perm.surf
pair.comp <- pairwiseAdonis::pairwise.adonis2(dist(t(d.clr.abund.filt.mh.surf), method='euclidean') ~ region, data=MH_env.surf, permutations = 9999)
pair.comp

# test for 'region, which has the most power.
# dispersion
disp.surf <- dist(t(d.clr.abund.filt.mh.surf), method = 'euclidean')
mh.bd.surf <- betadisper(disp.surf, MH_env.surf$region)
anova(mh.bd.surf)
permutest(mh.bd.surf)
boxplot(mh.bd.surf, xlab="Region",  col=c("gray", "red", "green"))

```

### PCA

```{r}
# prepare the data for PCA
pca.abund.surf <- t(d.clr.abund.filt.mh.surf) %>% as.data.frame() %>% rownames_to_column("Sample_ID") %>% 
  left_join(MH_env %>% rownames_to_column("Sample_ID") %>% select(Sample_ID, region)) 
cols_region <- c("north" = "khaki1", "central" = "cornflowerblue", "south" = "gray70")

# Write recipe for PCA
pca_rec <- recipe(~., data = pca.abund.surf) %>% # ~. because it is unsupervised
# Specify character_code as key/id column
  update_role(Sample_ID, region, new_role = 'id') %>% 
# normalize the data (center and scale all predictors (mean to zero and standard deviation of one)
  step_normalize(all_predictors()) %>%
# PCA is done here
# can use threshold to specify if we want to capture 90% of variance in the data (threshold = 0.9)
  step_pca(all_predictors(),  id = "pca") # for the bar plot showing how much variance each component accounts for

# 2 prep the recipe - values computed (prep() implements the recipe)
pca_prep <- prep(pca_rec)

# variance bar plot (variance explained)
total_variance_plot <- pca_prep %>%
  tidy(id = 'pca', type = 'variance') %>%
  dplyr::filter(terms == 'percent variance') %>%
  ggplot(aes(x = component, y = value)) +
  geom_col(fill = "lightblue") +
  # xlim(c(0,5))+
  labs(y = '% of total variance')

# for visualization = juice
pca.plot <- juice(pca_prep) %>% # juice() to return the results of a recipe
  mutate(region = fct_relevel(region, "north","central","south")) %>%
  ggplot(aes(PC1,PC2)) +
  geom_point(aes(color = region), alpha = 0.7, size =5) + 
  #geom_text(check_overlap = TRUE, hjust = 'inward', family = 'IBM Plex Sans') +
  geom_hline(yintercept=0, linetype="dashed", alpha = 0.3) +
  geom_vline(xintercept=0, linetype="dashed", alpha = 0.3) +
  # scale_colour_viridis_d(option = "plasma") 
 # scale_color_manual(values = cols_region) + 
   scale_colour_Publication()+
        theme_Publication_1()

# get % variation to add in the legend axis
var_explained <- pca_prep %>%
  tidy(id = 'pca', type = 'variance') %>%
  dplyr::filter(terms == 'percent variance') %>%
  pull(value)
pca.plot$labels$x <- paste0(pca.plot$labels$x," ", round(var_explained[1],2),"%")
pca.plot$labels$y <- paste0(pca.plot$labels$y," ", round(var_explained[2],2),"%")

# get PCA socres 
scores.pca <- juice(pca_prep) %>% select(-region) %>% column_to_rownames(var = 'Sample_ID')

# k-means clustering [assume 3 clusters]
km <- kmeans(scores.pca, centers= 6, nstart=5)

# add ellipses to PCA plot
k.bac <- factor(km$cluster)
pca.bac.surf <- pca.plot +  
  stat_ellipse(aes(x=PC1,y=PC2,group=k.bac),
               level=0.95, alpha=1, type = "norm", linetype = 2) +
        ggtitle("PCA: Bacterial Community at the surface") 

pca.bac.surf

ggsave(paste0(folder_path, "output/pca_surf_bac.tiff"), pca.bac.surf, compression = "lzw")

```

### Cluster analysis

```{r clustering}
# Cluster Analysis
# Determine number of clusters using factoextra
# First we will use enhanced k-means clustering
# Enhanced k-means clustering
res.km <- factoextra::eclust(t(d.clr.abund.filt.mh.surf), "kmeans", nstart = 25)

# Gap statistic plot
factoextra::fviz_gap_stat(res.km$gap_stat)
# Silhouette plot
factoextra::fviz_silhouette(res.km)
# Optimal number of clusters using gap statistics
res.km$nbclust
names <- res.km[["cluster"]]
names
# Print result
#res.km

# K-Means Cluster Analysis
mydata <- as.data.frame(t(d.clr.abund.filt.mh.surf))
mydata$fit.cluster <- NULL
fit <- kmeans(mydata, 4) 
# get cluster means
aggregate(mydata,by=list(fit$cluster),FUN=mean)
names.clust <- as.factor(mydata$fit.cluster)

factoextra::fviz_pca_ind(pcx.abund.surf, 
                habillage = MH_env.surf$region,
                pointshape = 21, pointsize = 2,
                #palette = "jco",
                addEllipses = TRUE,
                geom.var = F,
                repel = TRUE,
                #label="none",
                title = "PCA - Macquarie Harbour Surface") +
  theme(legend.direction = 'horizontal', legend.position = 'top')
```

### Mantel test

```{r mantel}

# Mantel test (mantel_test.R)
# https://jkzorz.github.io/2019/07/08/mantel-test.html

# SAMPLES as ROWS !!!!!

#abundance data frame
abund = data.frame(t(d.clr.abund.filt.mh.surf))
#abundance data frame - euclidean dissimilarity of clr-transf data (Aitchison distance)
dist.abund = vegdist(abund, method = "euclidean")

#create environmental data frame 
#make subset
env = MH_env.surf %>% select(DO, Salinity, Temperature, Nitrogen, Carbon, CN, TSSmean)
#scale data 
scale.env = scale(env, center = TRUE, scale = TRUE)
#create distance matrix of scaled data
dist.env = dist(scale.env, method = "euclidean")

#longitude and latitude 
geo = MH_env.surf %>% select(long, lat)
#geographic data frame - haversine distance 
d.geo = geosphere::distm(geo, fun = distHaversine)
dist.geo = as.dist(d.geo)

#run mantel test 
#abundance vs environmental
abund_env = mantel(dist.abund, dist.env, method = "spearman", permutations = 9999, na.rm = TRUE)
abund_env
#abundance vs geographic 
abund_geo  = mantel(dist.abund, dist.geo, method = "spearman", permutations = 9999, na.rm = TRUE)
abund_geo
# environmental vs geographic
env_geo  = mantel(dist.env, dist.geo, method = "spearman", permutations = 9999, na.rm = TRUE)
env_geo


# Partial Mantel tests
# geo distance controlled
abund_partial = mantel.partial(dist.abund, dist.env, dist.geo, method = "spearman", permutations = 9999, na.rm = TRUE)
abund_partial_envgeo
# env variability controlled
abund_partial = mantel.partial(dist.abund,  dist.geo, dist.env,method = "spearman", permutations = 9999, na.rm = TRUE)
abund_partial_geoenv   
  
# let's see each env factor alone
#environmental vector
env_fact = MH_env.surf$Salinity
#environmental vector - euclidean distance
dist.fact = dist(env_fact, method = "euclidean")

# environmental vs geographic
fact_geo  = mantel(dist.fact, dist.geo, method = "spearman", permutations = 9999, na.rm = TRUE)
fact_geo

#abundance vs env factor
abund_env_fact = mantel(dist.abund, dist.fact, method = "spearman", permutations = 9999, na.rm = TRUE)
abund_env_fact
```


```{r scatter plot}

# Scatter plots to show the relationship between two (usually continuous) variables. 

# Pairwise scatter plots
aa = as.vector(dist.abund)
tt = as.vector(dist.env)
#vv = as.vector(dist.fact)
gg = as.vector(dist.geo)

#abundance vs env parameters
mat = data.frame(aa,tt) #new data frame with vectorized distance matrices
lm = lm(aa~tt, data = mat)
summary(lm)
my.formula <- aa~tt
mm1 = ggplot(mat, aes(y = aa, x = tt)) + 
  geom_point(size = 3, alpha = 0.5, color = "gray50") + 
  labs(x = "Difference in Env Factors", y = "Euclidean Distance") + 
  geom_smooth(method = "lm", colour = "black", alpha = 0.2) +
  ggpmisc::stat_poly_eq(formula = my.formula, 
                        aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")), 
                        parse = TRUE,
                        label.x.npc = "left", label.y.npc = 75) +   
  ggpmisc::stat_fit_glance(method = 'lm',
                           geom = 'text',
                           aes(label = paste("P-value = ", signif(..p.value.., digits = 4),
                                             sep = "")))
  # theme( axis.text.x = element_text(face = "bold",colour = "black", size = 12), 
  #        axis.text.y = element_text(face = "bold", size = 11, colour = "black"), 
  #        axis.title= element_text(face = "bold", size = 14, colour = "black"), 
  #        panel.background = element_blank(), 
  #        panel.border = element_rect(fill = NA, colour = "black"))

mm1 <- mm1 + theme_Publication_1() +
  theme(panel.border = element_rect(fill = NA, colour = 'gray80'))

# abundance vs geographic distance
mat = data.frame(aa,gg) #new data frame with vectorized distance matrices
lm = lm(aa~gg)
summary(lm)
my.formula <- aa~gg
mm2 = ggplot(mat, aes(y = aa, x = gg/1000)) + 
  geom_point(size = 3, alpha = 0.5, color = "gray50") + 
  # geom_point(size = 4, alpha = 0.75, colour = "black",shape = 21, aes(fill = vv)) +
  labs(x = "Physical separation (km)", y = "Euclidean Distance") + 
  geom_smooth(method = "lm", colour = "black", alpha = 0.2) +
  # theme( axis.text.x = element_text(face = "bold",colour = "black", size = 12), 
  #        axis.text.y = element_text(face = "bold", size = 11, colour = "black"), 
  #        axis.title= element_text(face = "bold", size = 14, colour = "black"), 
  #        panel.background = element_blank(), 
  #        panel.border = element_rect(fill = NA, colour = "black")) +
  ggpmisc::stat_poly_eq(formula = my.formula, 
                        aes(label = paste(..eq.label.., ..rr.label..,sep = "~~~")), 
                        parse = TRUE,
                        label.x.npc = "left", label.y.npc = 75) +   
  ggpmisc::stat_fit_glance(method = 'lm',
                           geom = 'text',
                           aes(label = paste("P-value = ", signif(..p.value.., digits = 4),
                                             sep = ""))) 
mm2 <- mm2 + theme_Publication_1() +
  theme(panel.border = element_rect(fill = NA, colour = 'gray80'))

plots <- ggarrange(pca.plot, mm1, mm2, nrow = 3, labels = c("A", "B", "C"))

ggsave(paste0(folder_path, "output/pca_mantel_surf_bac.tiff"), plots, compression = "lzw", width = 9, height = 15)

```


```{r}
sessionInfo()
```

